# numpy

In [1]:
mylist = [1,2,3]

In [41]:
import numpy as np

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[6,7,8]]

In [7]:
myarrmat = np.array(my_mat)

In [8]:
myarrmat

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [16]:
np.linspace(0,100,50)

array([   0.        ,    2.04081633,    4.08163265,    6.12244898,
          8.16326531,   10.20408163,   12.24489796,   14.28571429,
         16.32653061,   18.36734694,   20.40816327,   22.44897959,
         24.48979592,   26.53061224,   28.57142857,   30.6122449 ,
         32.65306122,   34.69387755,   36.73469388,   38.7755102 ,
         40.81632653,   42.85714286,   44.89795918,   46.93877551,
         48.97959184,   51.02040816,   53.06122449,   55.10204082,
         57.14285714,   59.18367347,   61.2244898 ,   63.26530612,
         65.30612245,   67.34693878,   69.3877551 ,   71.42857143,
         73.46938776,   75.51020408,   77.55102041,   79.59183673,
         81.63265306,   83.67346939,   85.71428571,   87.75510204,
         89.79591837,   91.83673469,   93.87755102,   95.91836735,
         97.95918367,  100.        ])

In [17]:
np.linspace(0,10,4)

array([  0.        ,   3.33333333,   6.66666667,  10.        ])

In [18]:
np.linspace(0,10,25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [19]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [20]:
np.random.rand(4)

array([ 0.13395068,  0.41737837,  0.63199286,  0.03077566])

In [21]:
np.random.rand(2,3)

array([[ 0.00455293,  0.47915968,  0.37902435],
       [ 0.82743559,  0.56463929,  0.32272073]])

In [22]:
np.random.randn(10)

array([ 1.03586223,  1.94929159, -0.91389727, -1.08757133,  0.02946258,
       -2.27742366, -0.07263753, -1.0028137 , -0.57702385, -0.61124217])

# numbers from normal dist centered around 0

In [23]:
np.random.randn(4,4)

array([[ 1.42009052,  0.16974525,  0.78473516, -0.77110495],
       [ 0.32441687, -0.73422604,  0.52108822,  1.25135187],
       [ 0.31697593,  0.03461378,  1.12690907, -0.64782592],
       [ 0.87825978,  0.6133382 , -1.11765957, -1.07486199]])

In [24]:
np.random.randint(1,100)

87

In [25]:
np.random.randint(1,100,10)

array([44, 74, 91, 85, 18, 26, 30, 39, 12, 39])

In [26]:
#inclusive low end exclusive high end

In [27]:
arr = np.arange(1,25)

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([43, 23, 24,  4, 47,  6, 18, 35, 14, 13])

In [32]:
ranarr.reshape(2,5)

array([[43, 23, 24,  4, 47],
       [ 6, 18, 35, 14, 13]])

In [33]:
#number of rows times number of columns = total number of elements

In [34]:
ranarr.max()

47

In [35]:
ranarr.min()

4

In [36]:
ranarr.argmax()

4

In [38]:
ranarr.shape

(10,)

In [39]:
from numpy.random import randint

In [40]:
randint(2,3)

2

# numpy lesson 2

In [42]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arange1 = np.arange(0,10)

In [44]:
arange1[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arange1[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arange1[:5]

array([0, 1, 2, 3, 4])

In [48]:
arange1[5:7]

array([5, 6])

In [49]:
arr[0:5]=200

In [50]:
arr

array([200, 200, 200, 200, 200,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [51]:
sliceOf = arr[0:5]

In [52]:
sliceOf

array([200, 200, 200, 200, 200])

In [54]:
sliceOf[0:3]=100

In [55]:
arr

array([100, 100, 100, 200, 200,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [56]:
arrcopy = arr.copy()

In [57]:
arrcopy[0:5]=2

In [58]:
arr

array([100, 100, 100, 200, 200,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [59]:
arrcopy

array([ 2,  2,  2,  2,  2,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# 2d array

In [60]:
np_array = np.array([[1,2,3],[2,3,4],[5,6,7]])

In [61]:
np_array

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [62]:
np_array[0][2] #third column first row

3

In [63]:
np_array[0] # row 1

array([1, 2, 3])

In [65]:
np_array[:,2] #column 3

array([3, 4, 7])

In [67]:
np_array[:2,1:] # grab upper right corner

array([[2, 3],
       [3, 4]])

In [69]:
np_array[1:,1:]

array([[3, 4],
       [6, 7]])

In [70]:
linear = np.array([1,2,3,4,5,6,7,])

In [71]:
linear > 5

array([False, False, False, False, False,  True,  True], dtype=bool)

In [72]:
linear[linear > 5]

array([6, 7])

In [73]:
array2d = np.arange(0,50).reshape(5,10)

In [74]:
array2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
array2d[:3,5:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [76]:
array3 = np.arange(10)

In [77]:
array3+array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
array3*array3

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [80]:
array3 *10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
array3 / array3

/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [83]:
array3 / 0

/home/ubuntu/.local/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
array3 **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [85]:
np.sqrt(array3)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [86]:
np.exp(array3)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])